### PR TITLE
pkg/compute/rust: update messaging for 'rustup self update'

### LINKED ISSUE #269: Update rustup error to cover package managers
If `rustup` was installed via a package manager (e.g. homebrew) and needs to be updated, the provided instructions will not work:

```
error: self-update is disabled for this build of rustup
error: you should probably use your system package manager to update rustup
```

We might want to reword the instructions to cover this case.

Reported from @gaastonsr via #137.

### PR DESCRIPTION
**Pull request by Integralist**
Fixes #269

### CODE REVIEW

File: pkg/compute/rust.go [hunk 1]
```diff
@@ -153,9 +153,13 @@ func (r Rust) Verify(out io.Writer) error {
 		return fmt.Errorf("error parsing rustup constraint: %w", err)
 	}
 	if !rustupConstraint.Check(rustupVersion) {
+		pre := "To fix this error, run the following command"
+		cmd := text.Bold("rustup self update")
+		alt := fmt.Sprintf("%s If you installed rustup using a package manager, refer to its documentation to update it.", text.Bold("INFO:"))
```
Comment (kailan) [inline pkg/compute/rust.go:158]: perhaps "package manager such as Homebrew"?

Comment (Integralist) [reply pkg/compute/rust.go:158]: I had hoped to avoid calling out specific package managers (although admittedly the issue we're addressing has been reported because of Homebrew).

Comment (fgsch) [reply pkg/compute/rust.go:158]: What are we trying to accomplish by naming a specific package manager?

Personally I'd prefer if we don't, as this might be the case with any of them and/or might change in the future without our knowledge.

Comment (triblondon) [reply pkg/compute/rust.go:158]: I'm less worried about that and more about implying that we want the user to update their package manager 😂 .  I might say don't mention homebrew unless we can be sure that we're only doing that on MacOS platforms.

```suggestion
		alt := fmt.Sprintf("%s If you installed rustup using a package manager, you may need to follow your package manager's documentation to update the rustup package.", text.Bold("INFO:"))
```

**Review by kailan — APPROVED** [review]
