### PR TITLE
fix(service-version): Allow 'locked' services to be activated.

### LINKED ISSUE #1191: Can't activate version: "service version is not editable"
**Version**

```
Fastly CLI version v10.8.10 (7f391164)
Built with go version go1.22.2 linux/amd64 (2024-05-03)
```

**What happened**

I can't activate an older version.

My service has 8 versions:

```
fastly service describe --service-id=REDACTED
...
	Version 7/8
		Number: 7
		Comment: 
		Service ID: REDACTED
		Active: false
		Locked: true
		Deployed: false
		Staging: false
		Testing: false
		Created (UTC): 2024-04-30 15:33
		Last edited (UTC): 2024-05-03 15:33
	Version 8/8
		Number: 8
		Comment: 
		Service ID: REDACTED
		Active: true
		Locked: true
		Deployed: false
		Staging: false
		Testing: false
		Created (UTC): 2024-04-30 18:37
		Last edited (UTC): 2024-05-03 15:33
```

Trying to activate version 7 gives me the following error:

```
[~]$ fastly service-version activate --service-id=REDACTED --version=7

ERROR: service version 7 is not editable.

Repeat the command with the --autoclone flag to allow the version to be cloned
```

Note that I don't want to create a new version with `--autoclone`, I just want the older version to be activated.

I can activate version 7 using the Fastly API directly just fine:

```
http PUT "https://api.fastly.com/service/REDACTED/version/7/activate" Fastly-Key:REDACTED
{
    "active": true,
    "comment": "",
    "created_at": "2024-04-30T15:33:30Z",
    "deleted_at": null,
    "deployed": false,
    "locked": true,
    "msg": null,
    "number": 7,
    "service_id": "REDACTED",
    "staging": false,
    "testing": false,
    "updated_at": "2024-05-03T15:33:07Z"
}
```

### PR DESCRIPTION
**Pull request by kpfleming**
This PR changes the ServiceDetailsOpts structure (used by the ServiceDetails function) to permit commands to specify individual service states as part of the filtering mechanism. Nearly all commands allow both 'active' and 'locked' services, and previously 'service-version activate' blocked both, but it should allow 'locked' while still blocking 'active'.

Additionally, the error message emitted when the specified service is not allowed by the filter now indicates whether it was the 'active' or 'locked' status which caused the error.

Closes #1191.

### CODE REVIEW

File: pkg/commands/acl/describe.go [hunk 1]
```diff
@@ -64,7 +64,7 @@ func (c *DescribeCommand) Exec(_ io.Reader, out io.Writer) error {
 	}
 
 	serviceID, serviceVersion, err := argparser.ServiceDetails(argparser.ServiceDetailsOpts{
-		AllowActiveLocked:  true,
+		DisallowStates:     argparser.DisallowStateActive | argparser.DisallowStateLocked,
```
Comment (jsocol) [inline pkg/commands/acl/describe.go:67]: I'm possibly a little confused because we are flipping both the verb and some of the logic. `AllowActiveLocked: true` seems like it should correspond with `DisallowStateNone`, to allow both and disallow none. Is that an incorrect reading?

Comment (kpfleming) [reply pkg/commands/acl/describe.go:67]: You are not confused, that was a last-minute change before opening the PR for review and I did it very poorly. Will fix!

Comment (kpfleming) [reply pkg/commands/acl/describe.go]: This PR is not ready for review yet, but this area has been completely redesigned and the logic is now... logical.

File: pkg/commands/backend/backend_test.go [hunk 2]
```diff
@@ -30,9 +30,31 @@ func TestBackendCreate(t *testing.T) {
 			API: mock.API{
 				ListVersionsFn: testutil.ListVersions,
 			},
-			WantError: "service version 1 is not editable",
+			WantError: "service version 1 is active",
 		},
-		// The following test is the same as the above but it appends --autoclone
+		// The following test specifies a service version that's 'locked', and
+		// subsequently we expect it to not be cloned as we don't provide the
+		// --autoclone flag and trying to add a backend to an activated service
```
Comment (kpfleming) [inline pkg/commands/backend/backend_test.go:37]:
```suggestion
		// --autoclone flag and trying to add a backend to a locked service
```

File: pkg/commands/serviceversion/deactivate.go [hunk 3]
```diff
@@ -48,7 +49,7 @@ func NewDeactivateCommand(parent argparser.Registerer, g *global.Data) *Deactiva
 // Exec invokes the application logic for the command.
 func (c *DeactivateCommand) Exec(_ io.Reader, out io.Writer) error {
 	serviceID, serviceVersion, err := argparser.ServiceDetails(argparser.ServiceDetailsOpts{
-		AllowActiveLocked:  true,
+		Active:             optional.Of(true),
```
Comment (kpfleming) [inline pkg/commands/serviceversion/deactivate.go:52]: This is one of the actual bug fix changes: `fastly service-version deactivate` will now fail of the specified service-version is not active.

File: pkg/commands/serviceversion/lock.go [hunk 4]
```diff
@@ -48,7 +49,7 @@ func NewLockCommand(parent argparser.Registerer, g *global.Data) *LockCommand {
 // Exec invokes the application logic for the command.
 func (c *LockCommand) Exec(_ io.Reader, out io.Writer) error {
 	serviceID, serviceVersion, err := argparser.ServiceDetails(argparser.ServiceDetailsOpts{
-		AllowActiveLocked:  true,
+		Locked:             optional.Of(false),
```
Comment (kpfleming) [inline pkg/commands/serviceversion/lock.go:52]: This is one of the actual bug fix changes: `fastly service-version lock` will now fail if the specified service-version is locked.

File: pkg/commands/serviceversion/activate.go [hunk 5]
```diff
@@ -53,6 +54,7 @@ func NewActivateCommand(parent argparser.Registerer, g *global.Data) *ActivateCo
 // Exec invokes the application logic for the command.
 func (c *ActivateCommand) Exec(_ io.Reader, out io.Writer) error {
 	serviceID, serviceVersion, err := argparser.ServiceDetails(argparser.ServiceDetailsOpts{
+		Active:             optional.Of(false),
```
Comment (kpfleming) [inline pkg/commands/serviceversion/activate.go:57]: This is one of the actual bug fix changes: `fastly service-version activate` will now fail if the specified service-version is active, but will not fail if it is locked.

**Comment by Integralist** [comment]
It looks like a third-party dependency has been _manually_ copied into the repo?

From what I can tell the original code came from https://github.com/leighmcculloch/go-optional

We should be adding this as a dependency to the CLI `go.mod` 

e.g. `go get https://github.com/leighmcculloch/go-optional@latest` followed by `go mod tidy` once the dependency is referenced in the codebase itself)

**Comment by kpfleming** [comment]
The new package has now been added to `go.mod` as a normal dependency.

**Comment by kpfleming** [comment]
Unfortunately `go mod tidy` is not happy about the `replace` specification.

**Comment by Integralist** [comment]
I'll take a look on Monday and see what we can do

**Review by Integralist — APPROVED** [review]
Other than the issue with go mod tidy which I'll look at Monday, this LGTM

**Comment by Integralist** [comment]
Yeah I think we'll just have to use the import path used in that optional project...

```diff
diff --git a/go.mod b/go.mod
index b1c9b1bc..aaed6c53 100644
--- a/go.mod
+++ b/go.mod
@@ -79,8 +79,4 @@ require (
 	gopkg.in/yaml.v3 v3.0.1 // indirect
 )
 
-require (
-    github.com/leighmcculloch/go-optional v0.2.0
-)
-
-replace github.com/leighmcculloch/go-optional => 4d63.com/optional v0.2.0
+require 4d63.com/optional v0.2.0

diff --git a/pkg/argparser/cmd.go b/pkg/argparser/cmd.go
index 50e9ce62..3be4104b 100644
--- a/pkg/argparser/cmd.go
+++ b/pkg/argparser/cmd.go
@@ -13,7 +13,7 @@ import (
 	"github.com/fastly/cli/pkg/global"
 	"github.com/fastly/cli/pkg/manifest"
 	"github.com/fastly/cli/pkg/text"
-	optional "github.com/leighmcculloch/go-optional"
+	"4d63.com/optional"
 )
```

**Comment by kpfleming** [comment]
I know there are strong opinions about this topic, and I'm fairly new to the Golang community, but how would you feel about using 'go mod vendor' here? I'm mostly concerned about build reproducibility. Most of our dependencies are heavily-used packages and aren't likely to be a problem, but this one (`optional`) is not and could disappear.

**Comment by kpfleming** [comment]
After discussion with various knowledgeable Go users we've decided to stick with the 'vanity path' used for the `optional` module.
